spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment_processing_db
    username: gondasatishkumar
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: payment-group
      auto-offset-reset: earliest
      enable-auto-commit: false  # MANUAL mode
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.type.mapping: orderCreatedEvent:order.management.system.paymentprocessingservice.events.OrderCreatedEvent
        spring.json.trusted.packages: "*"
        spring.json.default.type: order.management.system.paymentprocessingservice.events.OrderCreatedEvent
    listener:
      ack-mode: manual  # Manual offset commit
      poll-timeout: 3000



